.class public LX/9V4;
.super Ljava/lang/Object;
.source ""


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:I

.field public A06:I

.field public A07:I

.field public A08:I

.field public A09:I

.field public A0A:I

.field public A0B:I

.field public A0C:I

.field public A0D:I

.field public A0E:I

.field public A0F:I

.field public A0G:J

.field public A0H:LX/AeG;

.field public A0I:LX/AeG;

.field public A0J:LX/AeJ;

.field public A0K:LX/AeV;

.field public A0L:LX/BXb;

.field public A0M:LX/AeE;

.field public A0N:LX/AeI;

.field public A0O:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0P:LX/AeM;

.field public A0Q:LX/AeH;

.field public A0R:LX/AeD;

.field public A0S:LX/AeO;

.field public A0T:LX/AeO;

.field public A0U:LX/AeF;

.field public A0V:Ljava/lang/String;

.field public A0W:Ljava/util/HashMap;

.field public A0X:Ljava/util/Map;

.field public A0Y:Ljava/util/Set;

.field public A0Z:Ljava/util/Set;

.field public A0a:Ljava/util/Set;

.field public A0b:Ljava/util/Set;

.field public A0c:Ljava/util/Set;

.field public A0d:Ljava/util/Set;

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z

.field public A0m:Z

.field public A0n:Z

.field public A0o:Z

.field public A0p:Z


# direct methods
.method public constructor <init>()V
    .locals 7

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/9V4;->A0o:Z

    sget-object v0, LX/AeW;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/9V4;->A0O:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    const/4 v2, 0x1

    iput-boolean v1, p0, LX/9V4;->A0f:Z

    const/4 v0, 0x3

    iput v0, p0, LX/9V4;->A07:I

    const/16 v3, 0x7d0

    const-string v0, "ExoService"

    iput-object v0, p0, LX/9V4;->A0V:Ljava/lang/String;

    const/16 v6, 0xfa

    iput-boolean v2, p0, LX/9V4;->A0n:Z

    new-instance v0, LX/9Vd;

    invoke-direct {v0}, LX/9Vd;-><init>()V

    iget-boolean v2, v0, LX/9Vd;->A00:Z

    new-instance v0, LX/AeI;

    invoke-direct {v0, v2}, LX/AeI;-><init>(Z)V

    iput-object v0, p0, LX/9V4;->A0N:LX/AeI;

    const/16 v2, 0x3e8

    const/16 v5, 0x1f4

    new-instance v0, LX/AeO;

    invoke-direct {v0, v5, v3}, LX/AeO;-><init>(II)V

    iput-object v0, p0, LX/9V4;->A0S:LX/AeO;

    new-instance v0, LX/AeO;

    invoke-direct {v0, v1, v1}, LX/AeO;-><init>(II)V

    iput-object v0, p0, LX/9V4;->A0T:LX/AeO;

    new-instance v0, LX/AeM;

    invoke-direct {v0}, LX/AeM;-><init>()V

    iput-object v0, p0, LX/9V4;->A0P:LX/AeM;

    new-instance v0, LX/99a;

    invoke-direct {v0}, LX/99a;-><init>()V

    new-instance v0, LX/BXb;

    invoke-direct {v0}, LX/BXb;-><init>()V

    iput-object v0, p0, LX/9V4;->A0L:LX/BXb;

    sget-object v0, LX/AeV;->A00:LX/AeV;

    iput-object v0, p0, LX/9V4;->A0K:LX/AeV;

    new-instance v0, LX/99U;

    invoke-direct {v0}, LX/99U;-><init>()V

    new-instance v0, LX/AeJ;

    invoke-direct {v0}, LX/AeJ;-><init>()V

    iput-object v0, p0, LX/9V4;->A0J:LX/AeJ;

    new-instance v0, LX/99b;

    invoke-direct {v0}, LX/99b;-><init>()V

    new-instance v0, LX/AeE;

    invoke-direct {v0}, LX/AeE;-><init>()V

    iput-object v0, p0, LX/9V4;->A0M:LX/AeE;

    new-instance v0, LX/99d;

    invoke-direct {v0}, LX/99d;-><init>()V

    new-instance v0, LX/AeF;

    invoke-direct {v0}, LX/AeF;-><init>()V

    iput-object v0, p0, LX/9V4;->A0U:LX/AeF;

    new-instance v0, LX/AeD;

    invoke-direct {v0}, LX/AeD;-><init>()V

    iput-object v0, p0, LX/9V4;->A0R:LX/AeD;

    new-instance v4, LX/9RD;

    invoke-direct {v4}, LX/9RD;-><init>()V

    const v0, 0x186a0

    iput v0, v4, LX/9RD;->A00:I

    iput v2, v4, LX/9RD;->A03:I

    iput v5, v4, LX/9RD;->A02:I

    iput v6, v4, LX/9RD;->A01:I

    new-instance v0, LX/AeG;

    invoke-direct {v0, v4}, LX/AeG;-><init>(LX/9RD;)V

    iput-object v0, p0, LX/9V4;->A0H:LX/AeG;

    new-instance v4, LX/9RD;

    invoke-direct {v4}, LX/9RD;-><init>()V

    iput v3, v4, LX/9RD;->A00:I

    const v0, 0x249f0

    iput v0, v4, LX/9RD;->A03:I

    const v0, 0x86470

    iput v0, v4, LX/9RD;->A02:I

    const v0, 0x1e8480

    iput v0, v4, LX/9RD;->A01:I

    new-instance v0, LX/AeG;

    invoke-direct {v0, v4}, LX/AeG;-><init>(LX/9RD;)V

    iput-object v0, p0, LX/9V4;->A0I:LX/AeG;

    iput-boolean v1, p0, LX/9V4;->A0g:Z

    iput-boolean v1, p0, LX/9V4;->A0i:Z

    const/16 v6, 0xfa0

    invoke-static {}, LX/000;->A10()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0W:Ljava/util/HashMap;

    const-wide/16 v4, 0x0

    iput-wide v4, p0, LX/9V4;->A0G:J

    invoke-static {}, LX/000;->A10()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0X:Ljava/util/Map;

    const/16 v0, 0x7530

    iput v0, p0, LX/9V4;->A04:I

    const/4 v0, -0x1

    iput v0, p0, LX/9V4;->A0D:I

    iput v6, p0, LX/9V4;->A03:I

    invoke-static {}, LX/1kg;->A14()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0b:Ljava/util/Set;

    invoke-static {}, LX/1kg;->A14()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0a:Ljava/util/Set;

    invoke-static {}, LX/1kg;->A14()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0c:Ljava/util/Set;

    new-instance v0, LX/AeH;

    invoke-direct {v0}, LX/AeH;-><init>()V

    iput-object v0, p0, LX/9V4;->A0Q:LX/AeH;

    invoke-static {}, LX/1kg;->A14()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0Z:Ljava/util/Set;

    invoke-static {}, LX/1kg;->A14()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0Y:Ljava/util/Set;

    invoke-static {}, LX/1kg;->A14()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/9V4;->A0d:Ljava/util/Set;

    const/16 v0, 0x28

    iput v0, p0, LX/9V4;->A0C:I

    iput v0, p0, LX/9V4;->A0B:I

    iput v1, p0, LX/9V4;->A08:I

    const/4 v0, -0x1

    iput v0, p0, LX/9V4;->A09:I

    iput v0, p0, LX/9V4;->A0E:I

    iput v2, p0, LX/9V4;->A06:I

    iput v3, p0, LX/9V4;->A05:I

    iput v2, p0, LX/9V4;->A00:I

    iput v2, p0, LX/9V4;->A02:I

    const v0, 0x8000

    iput v0, p0, LX/9V4;->A01:I

    iput-boolean v1, p0, LX/9V4;->A0h:Z

    iput-boolean v1, p0, LX/9V4;->A0e:Z

    iput-boolean v1, p0, LX/9V4;->A0m:Z

    const/16 v0, 0x18

    iput v0, p0, LX/9V4;->A0A:I

    iput-boolean v1, p0, LX/9V4;->A0p:Z

    const/4 v0, -0x1

    iput v0, p0, LX/9V4;->A0F:I

    return-void
.end method
